// End-to-end run of the v3 "done" test (done-test.md) in Chromium, with the iPhone shell and the internet faked.
// Usage: node dev/test/e2e.mjs
import { chromium } from 'playwright';
import http from 'http';
import fs from 'fs';
import path from 'path';
import { installFakes, CAP, CHANNELS } from './fakenet.mjs';

const root = new URL('../../', import.meta.url).pathname;
const server = http.createServer((req, res) => {
  const f = path.join(root, decodeURIComponent(req.url.split('?')[0]).replace(/\/$/, '/index.html'));
  fs.readFile(f, (e, d) => { if (e) { res.writeHead(404); res.end(); return; } res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); res.end(d); });
}).listen(8765);
const URL0 = 'http://localhost:8765/';
const SHOTS = '/tmp/claude-0/-home-claude/37d1ef24-0e4b-56e8-ae27-d473dfebb3f7/scratchpad';

let failures = 0;
const ok = (cond, msg) => { console.log((cond ? '  PASS ' : '  FAIL ') + msg); if (!cond) failures++; };
const errors = [];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--autoplay-policy=no-user-gesture-required'] });
const phone = { viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true };

async function appPage({ prefs = {}, clip = '', fakes = {}, ctxOpts = {}, shell = {} } = {}) {
  const ctx = await browser.newContext({ ...phone, ...ctxOpts });
  await installFakes(ctx, fakes);
  // Shelf orders Home by the time of day; tests run at mid-afternoon unless they say otherwise
  await ctx.addInitScript('window.__hour = ' + (shell.hour ?? 14.13) + ';');
  await ctx.addInitScript(CAP(prefs, clip, shell));
  const p = await ctx.newPage();
  p.on('pageerror', (e) => errors.push(e.message));
  p.on('console', (m) => { if (m.type() === 'error' && !/Failed to load resource|net::ERR/.test(m.text())) errors.push(m.text()); });
  await p.goto(URL0);
  return { ctx, p };
}
const settle = (p) => p.waitForFunction(() => window.__shelf && !window.__shelf.busy, null, { timeout: 10000 }).then(() => p.waitForTimeout(150)).catch(() => {});
const shelf = (p, fn) => p.evaluate(fn);

console.log('\n== 1 Open');
let { ctx, p } = await appPage({ fakes: { fresh: true } });
await settle(p);
const names = await p.locator('.band .hd h2').allTextContents();
ok(names.join(',') === 'Entertainment,Medicine,Sleep,Pasted', '1 order: Entertainment, Medicine, Sleep, Pasted last: ' + names.join(', '));
ok(await p.locator('#bands .addcat').count() === 1, '1 an Add category line under Pasted');
ok(await shelf(p, () => window.__shelf.lib.sources().length) === 7, '1 all seven of Mo\'s channels found on first run');
await p.waitForFunction(() => document.querySelector('#statusDot').classList.contains('good'), null, { timeout: 6000 }).catch(() => {});
ok(await p.locator('#statusDot.good').count() === 1 && (await p.locator('#statusText').textContent()) === 'All good', '1 corner says All good');
ok(await p.locator('.band .nw').count() === 0, '1 nothing marked new on the very first run');
const calls = await shelf(p, () => window.__httpCalls);
ok(calls.some((c) => /youtube\.com\/@/.test(c.url) && /SOCS=/.test(c.headers.Cookie) && /Macintosh/.test(c.headers['User-Agent'])), '1 channel pages are read natively, with the consent cookie and a desktop identity (the phone page is shaped differently)');

console.log('\n== 2 New uploads');
await shelf(p, () => window.__shelf.refreshAll(true)); await settle(p);
ok(await p.locator('.band ul').count() === 0 && await p.locator('.band .tg[aria-expanded="false"]').count() === 3 && await p.locator('.band.c0 .urlb').count() === 1, '2 Pasted has a + URL button; Home starts with every section folded');
ok(!/days to Step 2 CK|unfinished/.test(await p.locator('#home').textContent()), '2 Home has no exam countdown or tallies');
await p.locator('.band.c1 .tg').click(); await p.waitForTimeout(100);
ok(await p.locator('.band.c1 .nw').count() === 3 && await shelf(p, () => !!window.__shelf.prefs.open.med), '2 tapping Medicine unfolds it (remembered): 3 NEW uploads');
ok((await p.locator('.band.c1 .tm').textContent()).includes('3 new'), '2 Medicine header says 3 new');
await p.locator('.band.c1 .hd .tm').click();
ok(await p.locator('#page .top h1').textContent() === 'Medicine' && !(await p.locator('#page .chrow').first().isVisible()), '2 the count opens Medicine, channels folded under the videos');
await p.locator('#page details.fold summary', { hasText: 'Channels' }).click();
ok(await p.locator('#page .chrow').count() === 3, '2 Medicine page lists its 3 channels');
await p.locator('#page .chrow', { hasText: 'Dirty Medicine' }).click();
ok(await p.locator('#page .item').count() === 3 && await p.locator('#page .item .nw').count() === 1, '2 channel shows its latest videos with the new one marked (' + await p.locator('#page .item').count() + ' items, ' + await p.locator('#page .item .nw').count() + ' new)');
ok(!(await p.content()).toLowerCase().includes('recommended'), '2 no recommendations anywhere');
await p.locator('[data-act="back"]').click(); await p.waitForTimeout(150);
await p.locator('[data-act="back"]').click(); await p.waitForTimeout(150);
ok(await p.locator('.band.c1 .nw').count() === 2, '2 opening the channel clears its new mark');
const savedPrefs = await shelf(p, () => window.__prefs);
ok(!!savedPrefs['shelf.v2.library'], '2 channel list saved on the phone');

console.log('\n== 3 A link in Search');
await p.locator('#searchBtn').click();
await p.fill('#sq', 'https://youtu.be/dQw4w9WgXcQ?si=xyz'); await p.press('#sq', 'Enter'); await p.waitForTimeout(500);
ok(await p.locator('#vsheet.open').count() === 1 && await shelf(p, () => window.__shelf.current) === 'dQw4w9WgXcQ', '3 a YouTube link typed or pasted into Search plays');
ok(await shelf(p, () => window.__fake.getPlayerState()) === 1, '3 it is playing');

console.log('\n== 4 Resume');
await p.evaluate(() => window.__fake.advance(60));
await p.waitForTimeout(5400);
const t = await shelf(p, () => window.__shelf.videos.dQw4w9WgXcQ.t);
ok(t > 55 && t < 80, '4 spot saved around 1:00 (got ' + t.toFixed(1) + ')');
await p.waitForTimeout(400);
const prefs4 = await shelf(p, () => window.__prefs);
await ctx.close();
({ ctx, p } = await appPage({ prefs: prefs4 })); // web storage gone, phone storage kept: like a fresh launch
await p.waitForTimeout(1200);
ok(await p.locator('#cont').isVisible() && /1:\d\d/.test(await p.locator('#contMeta').textContent()), '4 Resume strip shows it at ' + await p.locator('#contMeta').textContent());
await p.locator('#cont').click(); await p.waitForTimeout(400);
const start = await shelf(p, () => window.__lastStart);
ok(Math.abs(start - (t - 3)) < 2, '4 one tap carries on from the saved spot (start ' + start + ')');

console.log('\n== 5 Sleep timer (video)');
ok(!(await p.locator('#vSeg').isVisible()) && (await p.locator('#vStops').textContent()) === 'Off', '5 sleep timer starts folded, saying Off');
await p.locator('#vTmBtn').click();
await p.locator('#vSeg [data-m="15"]').click();
ok(/14:5\d|15:00/.test(await p.locator('#vStops').textContent()) && (await p.locator('#vStops').textContent()).includes('stops'), '5 countdown shows: ' + await p.locator('#vStops').textContent());
await p.evaluate(() => { window.__shelf.vTimer.endsAt = Date.now() + 1200; });
await p.waitForTimeout(2600);
ok(await shelf(p, () => window.__fake.getPlayerState()) === 2, '5 video pauses when the timer hits zero');
ok((await p.locator('#vStops').textContent()).includes('Paused by the sleep timer'), '5 says it was the sleep timer');
const b15 = p.locator('#vSeg [data-m="15"]').first(); const bb = await b15.boundingBox();
await p.mouse.move(bb.x + 10, bb.y + 10); await p.mouse.down(); await p.waitForTimeout(800); await p.mouse.up(); await p.waitForTimeout(100);
ok(await shelf(p, () => window.__shelf.vTimer && window.__shelf.vTimer.minutes) === 1 && /[01]:\d\d/.test(await p.locator('#vStops').textContent()), '5 press and hold sets a 1-minute test timer');
await p.locator('#vSeg [data-m="30"]').click(); await p.locator('#vSeg [data-m="30"]').click();
ok(await p.locator('#vSeg').isVisible(), '5 the numbers stay open after turning the timer off');
ok((await p.locator('#vStops').textContent()).startsWith('Off'), '5 tapping the chosen number again turns the timer off');
// guards from v1: video swap and pre-roll ads must not overwrite a spot
await p.evaluate(() => { window.__lag = true; });
await p.locator('[data-act="close-video"]').click();
await shelf(p, () => window.__shelf.handleText('https://youtu.be/swapswapswa')); await p.waitForTimeout(100);
await shelf(p, () => window.__shelf.capture(true));
ok((await shelf(p, () => window.__shelf.videos.swapswapswa.t)) < 5, 'swap: the new video keeps its own spot');
await p.waitForTimeout(600); await p.evaluate(() => { window.__lag = false; window.__ad = true; });
await p.locator('[data-act="close-video"]').click();
await shelf(p, () => window.__shelf.handleText('https://youtu.be/dQw4w9WgXcQ'));
await shelf(p, () => window.__shelf.capture(true));
const adV = await shelf(p, () => ({ ...window.__shelf.videos.dQw4w9WgXcQ }));
ok(!adV.done && adV.t > 50 && adV.dur === 600, 'ad: spot kept (t ' + adV.t.toFixed(0) + ', dur ' + adV.dur + ')');
await p.waitForTimeout(600); await p.evaluate(() => { window.__ad = false; });
await p.locator('[data-act="close-video"]').click();
await ctx.close();

console.log('\n== 6 Sleep audio and lock screen');
({ ctx, p } = await appPage({ fakes: { fresh: false, feedDown: ['@MehlmanMedical'] } }));
await settle(p);
await p.locator('.band.c3 .tg').click();
ok(await p.locator('.band.c3 ul').count() === 0 && await p.locator('.band.c3 .chl button').count() === 2 && /latest/.test(await p.locator('.band.c3 .chl').textContent()), '6 nothing new: the open Sleep band lists its channels, each with its latest');
await p.locator('.band.c1 .tg').click(); await p.waitForTimeout(100);
await p.locator('.band.c1 .chl button', { hasText: 'Mehlman Medical' }).click(); await p.waitForTimeout(200);
const chTitles = await p.locator('#page .item .t').allTextContents();
ok(await p.locator('#page .top h1').textContent() === 'Mehlman Medical' && /Renal/.test(chTitles[0]), '6 tapping a channel in the band opens it, newest video first: ' + chTitles.slice(0, 2).join(' | '));
ok(await p.locator('#page .err').count() === 0 && (await shelf(p, () => window.__httpCalls.some((c) => /\/channel\/UC\w+\/videos$/.test(c.url)))), "6 Mehlman's feed is broken (500) but the channel still loads from its Videos tab, no \"Couldn't update\"");
await p.locator('#todayBtn').click(); await p.waitForTimeout(150);
await p.locator('.band.c3 .hd .tm').click();
await p.locator('#page .item', { hasText: 'Rome' }).click(); await p.waitForTimeout(1200);
ok(await p.locator('#nsheet.open').count() === 1, '6 night player opens');
ok(await p.evaluate(() => !document.querySelector('#audio').paused), '6 episode is playing');
ok(await p.evaluate(() => navigator.mediaSession && navigator.mediaSession.metadata && navigator.mediaSession.metadata.title) === 'Rome: The Fall of the Western Empire', '6 lock screen shows the episode title');
await p.locator('#nSeg [data-m="15"]').click();
ok(/1[45]:\d\d/.test(await p.locator('#nCd').textContent()), '6 "lights out in" countdown shows');
await p.locator('[data-act="close-night"]').click();
await p.locator('[data-act="back"]').click(); await p.waitForTimeout(150);
ok(await p.locator('#mini').isVisible() && /to sleep/.test(await p.locator('#miniSub').textContent()), '6 keeps playing with a mini bar after closing: ' + await p.locator('#miniSub').textContent());
await p.locator('#todayBtn').click(); await p.waitForTimeout(150);
ok(!(await p.locator('#cont').isVisible() && /Rome/.test(await p.locator('#contTitle').textContent())), '6 the podcast shows once (in the bar), not again as Continue');
await p.evaluate(() => { window.__shelf.engine.state().timer.endsAt = Date.now() + 1500; });
await p.waitForTimeout(3000);
ok(await p.evaluate(() => document.querySelector('#audio').paused), '6 stops when the timer runs out');
const ep = await shelf(p, () => Object.values(window.__shelf.audio)[0]);
ok(ep && ep.t > 1 && ep.source, '6 episode spot saved (' + (ep && ep.t.toFixed(1)) + 's)');
ok(await p.evaluate(() => document.querySelector('#audio').volume) === 1, '6 volume back to normal for next time');

console.log('\n== 7 Search and add');
await p.locator('#searchBtn').click();
await p.fill('#sq', 'renal'); await p.press('#sq', 'Enter'); await p.waitForTimeout(500);
ok(await p.locator('#page .item').count() >= 1 && (await p.locator('#page .item').first().textContent()).includes('Renal'), '7 search shows results');
await p.locator('#page .item').first().click(); await p.waitForTimeout(400);
ok(await p.locator('#vsheet.open').count() === 1 && await shelf(p, () => window.__fake.getPlayerState()) === 1, '7 a result plays');
await p.locator('[data-act="close-video"]').click();
await p.locator('[data-act="back"]').click(); await p.waitForTimeout(150);
await p.locator('#todayBtn').click(); await p.waitForTimeout(150);
await p.locator('#bands .addcat').click(); await p.waitForTimeout(100);
ok(/New category/.test(await p.locator('#secH').textContent()), '7 + Add category on Home opens New category');
await p.fill('#secName', 'Revision'); await p.locator('#secForm [type="submit"]').click(); await p.waitForTimeout(150);
await p.locator('#todayBtn').click(); await p.waitForTimeout(150);
ok((await p.locator('.band .hd h2').allTextContents()).join(',') === 'Entertainment,Medicine,Sleep,Revision,Pasted', '7 the new category sits after Sleep, Pasted stays last: ' + (await p.locator('.band .hd h2').allTextContents()).join(','));
await p.locator('.band', { hasText: 'Revision' }).locator('.tg').click();
await p.locator('.band', { hasText: 'Revision' }).locator('[data-act="add-channel"]').click();
await p.fill('#addInput', 'https://www.youtube.com/@MehlmanMedical'); await p.locator('#addGo').click();
await p.waitForTimeout(600);
ok(/Added Mehlman Medical to Revision/.test(await p.locator('#addMsg').textContent()), '7 add channel by pasting its link: ' + await p.locator('#addMsg').textContent());
await p.waitForTimeout(800);
await p.locator('.band', { hasText: 'Revision' }).locator('.hd .tm').click();
await p.locator('[data-act="add-channel"]').first().click();
await p.fill('#addInput', 'https://www.youtube.com/@NoSuchChannel'); await p.locator('#addGo').click(); await p.waitForTimeout(500);
ok(/Not found/.test(await p.locator('#addMsg').textContent()), '7 a bad channel is explained: ' + await p.locator('#addMsg').textContent());
await p.keyboard.press('Escape');
await p.locator('[data-act="back"]').click(); await p.waitForTimeout(150);

console.log('\n== 8 Self-check');
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
const txt = await p.locator('#checkList').textContent();
ok(await p.locator('#checkList li.ok').count() >= 6 && txt.includes('Running inside the Shelf app'), '8 green ticks in the app');
ok(!(await p.locator('#toneBtn').isVisible()) && !(await p.locator('#sendBtn').isVisible()), '8 extras are folded under More');
await p.locator('#checkMore summary').click();
ok(await p.locator('#toneBtn').isVisible(), '8 lock-screen sound test is offered in the app');
ok(txt.includes('Signed in to YouTube') && (await p.locator('#ytBtn').textContent()) === 'Sign out of YouTube', '8 says it is signed in to YouTube, with a way out');
ok(!(await p.locator('#retryBtn').isVisible()), '8 no Try again when phone storage is fine');
await p.screenshot({ path: SHOTS + '/e2e-check.png' });
await p.keyboard.press('Escape');
ok(await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'phone: no sideways scroll');
await ctx.close();

console.log('\n== Player for keyboards and VoiceOver');
({ ctx, p } = await appPage());
await settle(p);
await p.focus('#statusBtn');
await shelf(p, () => window.__shelf.handleText('https://youtu.be/dQw4w9WgXcQ')); await p.waitForTimeout(600);
ok(await p.evaluate(() => ['#home', 'nav.tabs'].every((q) => document.querySelector(q).inert) && !document.querySelector('#vsheet').inert), 'a11y: the page behind the player is inert');
let escaped = 0;
for (let i = 0; i < 14; i++) { await p.keyboard.press('Tab'); if (await p.evaluate(() => { const a = document.activeElement; return a && a !== document.body && !document.querySelector('#vsheet').contains(a); })) escaped++; }
ok(escaped === 0, 'a11y: Tab stays inside the player (' + escaped + ' escapes)');
await p.evaluate(() => window.__fake.advance(100)); await p.waitForTimeout(1300);
await p.focus('#vScrub'); await p.keyboard.press('Space'); await p.waitForTimeout(200);
let pos = await shelf(p, () => window.__fake.getCurrentTime());
ok(pos > 90, 'a11y: Space on the position line doesn\'t jump to the start (' + Math.round(pos) + ')');
await p.keyboard.press('ArrowRight'); await p.waitForTimeout(200);
const pos2 = await shelf(p, () => window.__fake.getCurrentTime());
ok(pos2 - pos > 12 && pos2 - pos < 18, 'a11y: arrow keys step through the video like its +15 button (+' + Math.round(pos2 - pos) + ' s)');
ok(Number(await p.getAttribute('#vScrub', 'aria-valuenow')) > 90 && /of/.test(await p.getAttribute('#vScrub', 'aria-valuetext')), 'a11y: the position line reads as a slider with its time');
const yt = await p.evaluate(() => { const a = document.querySelector('#ytLink'); a.addEventListener('click', (e) => e.preventDefault(), { once: true }); a.click(); return a.href; });
const at = +(yt.match(/[?&]t=(\d+)s/) || [])[1];
ok(at > 100 && /^youtube:\/\/www\.youtube\.com\/watch\?v=/.test(yt), 'Play locked ↗ opens the YouTube app (youtube://) at the spot playing now (t=' + at + ')');
const hand = await shelf(p, () => JSON.parse(localStorage.getItem('shelf.handoff')));
ok(hand && Math.abs(hand.t - at) < 2 && await shelf(p, () => window.__fake.getPlayerState()) !== 1, 'Play locked ↗ pauses Shelf and remembers where it handed over');
await shelf(p, () => { Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => 'hidden' }); document.dispatchEvent(new Event('visibilitychange')); delete document.visibilityState; });
ok(await shelf(p, () => JSON.parse(localStorage.getItem('shelf.handoff')).armed === true), 'the hand-off counts once Shelf actually goes to YouTube');
await shelf(p, () => { const h = JSON.parse(localStorage.getItem('shelf.handoff')); h.at -= 180e3; localStorage.setItem('shelf.handoff', JSON.stringify(h)); window.__shelf.catchUp(); });
await p.waitForTimeout(200);
const back = await shelf(p, () => { const v = window.__shelf.videos[window.__shelf.current]; return { t: v.t, toast: document.querySelector('#toast').textContent, fake: window.__fake.getCurrentTime() }; });
ok(Math.abs(back.t - (hand.t + 180 * hand.rate)) < 3 && /Moved your place to .* for the time you were in YouTube/.test(back.toast) && Math.abs(back.fake - back.t) < 3, 'back from YouTube 3 min later: place and player move on 3 min (' + Math.round(hand.t) + ' -> ' + Math.round(back.t) + ' s)');
await p.locator('#toast button', { hasText: 'Undo' }).click(); await p.waitForTimeout(150);
const undoOk = Math.abs(await shelf(p, () => window.__shelf.videos[window.__shelf.current].t) - hand.t) < 2 && await shelf(p, () => localStorage.getItem('shelf.handoff')) === 'null';
// Away longer than the video: stops just before the end, not marked watched
await p.evaluate((h) => { localStorage.setItem('shelf.handoff', JSON.stringify(Object.assign({}, h, { at: Date.now() - 3 * 3600e3, armed: true }))); window.__shelf.catchUp(); }, hand);
const end = await shelf(p, () => window.__shelf.videos[window.__shelf.current]);
ok(end.dur > 0 && end.t === end.dur - 30 && !end.done, 'away longer than the video: place stops 30 s before the end, not ticked (' + Math.round(end.t) + ' of ' + Math.round(end.dur) + ')');
await p.locator('#toast button', { hasText: 'Undo' }).click(); await p.waitForTimeout(150);
ok(undoOk, 'Undo puts the place back; the hand-off is used once');
await shelf(p, () => window.__shelf.catchUp());
// A tap that never left Shelf (cancelled), or a night away, doesn't move anything
await p.evaluate((h) => { localStorage.setItem('shelf.handoff', JSON.stringify(Object.assign({}, h, { at: Date.now() - 600e3 }))); window.__shelf.catchUp(); }, hand);
await p.evaluate((h) => { localStorage.setItem('shelf.handoff', JSON.stringify(Object.assign({}, h, { at: Date.now() - 10 * 3600e3, armed: true }))); window.__shelf.catchUp(); }, hand);
ok(Math.abs(await shelf(p, () => window.__shelf.videos[window.__shelf.current].t) - hand.t) < 2, 'a second return, a cancelled tap, or a night away does nothing');
// Auto-lock: set up once from the dialog; Play locked then runs the "Shelf Play Locked" Shortcut with the YouTube link
await shelf(p, () => { const b = document.createElement('button'); b.setAttribute('data-act', 'lock-setup'); document.body.appendChild(b); b.click(); b.remove(); });
await p.waitForTimeout(200);
ok(await p.locator('#lockDlg[open]').count() === 1 && /Lock Screen/.test(await p.locator('#lockDlg').textContent()), 'auto-lock: the setup sheet explains the 3-step Shortcut');
await p.locator('#lockToggle').click(); await p.waitForTimeout(150);
ok(await shelf(p, () => window.__shelf.prefs.autoLock === true) && /Auto-lock is on/.test(await p.locator('#lockToggle').textContent()), 'auto-lock: turned on and remembered');
await p.keyboard.press('Escape'); await p.waitForTimeout(200);
const sc = await p.evaluate(() => { const a = document.querySelector('#ytLink'); a.addEventListener('click', (e) => e.preventDefault(), { once: true }); a.click(); return a.href; });
ok(/^shortcuts:\/\/run-shortcut\?name=Shelf%20Play%20Locked&input=text&text=youtube%3A%2F%2Fwww\.youtube\.com%2Fwatch%3Fv%3D/.test(sc), 'auto-lock: Play locked runs the Shortcut with the YouTube app link');
await shelf(p, () => { window.__shelf.prefs.autoLock = false; localStorage.setItem('shelf.handoff', 'null'); });
// Locking while it plays in Shelf (no hand-off): back in Shelf, a hint with a Play locked button
await shelf(p, () => window.__fake.playVideo()); await p.waitForTimeout(300);
await shelf(p, () => { const vis = (v) => { Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => v }); document.dispatchEvent(new Event('visibilitychange')); delete document.visibilityState; }; vis('hidden'); vis('visible'); });
await p.waitForTimeout(150);
ok(/stops videos inside other apps when the phone locks/.test(await p.locator('#toast').textContent()) && await p.locator('#toast button', { hasText: 'Play locked' }).count() === 1 && await shelf(p, () => window.__fake.getPlayerState()) !== 1, 'locked while playing in Shelf: paused, and the hint offers Play locked');
await p.keyboard.press('Escape'); await p.waitForTimeout(400);
ok(await p.evaluate(() => !document.querySelector('#home').inert && document.activeElement && document.activeElement.id === 'statusBtn'), 'a11y: closing hands focus back to what opened it');
await ctx.close();

console.log('\n== YouTube sign-in (Premium without ads)');
({ ctx, p } = await appPage({ shell: { ytSignedIn: false } }));
await settle(p);
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
ok(/Not signed in to YouTube, so videos play with ads/.test(await p.locator('#checkList').textContent()) && await p.locator('#statusDot.bad').count() === 1, 'YT signed out is explained and the corner needs a look');
ok(await p.locator('#ytBtn').isVisible() && (await p.locator('#ytBtn').textContent()) === 'Sign in to YouTube', 'YT offers Sign in to YouTube');
ok(/One thing to fix/.test(await p.locator('#checkVerdict').textContent()) && await p.locator('#checkProblems .prob:not(.wait)').count() === 1 && /1 problem/.test(await p.locator('#statusText').textContent()), 'verdict: one thing to fix, shown on its own with its button');
const reloaded = p.waitForEvent('load', { timeout: 5000 }).then(() => true, () => false);
await p.locator('#ytBtn').click();
ok(await reloaded, 'YT after the sheet closes signed in, the page reloads so the player sees the account');
await settle(p);
await p.waitForFunction(() => document.querySelector('#statusDot').classList.contains('good'), null, { timeout: 6000 }).catch(() => {});
ok(await shelf(p, () => window.__ytCalls.length) === 0 && await p.locator('#statusDot.good').count() === 1, 'YT fresh page is all good');
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
ok(/Signed in to YouTube.*Allow Cross-Website Tracking/.test(await p.locator('#checkList').textContent()), 'YT signed in, and says what else Premium needs');
ok(/All good/.test(await p.locator('#checkVerdict').textContent()) && await p.locator('#checkProblems .prob:not(.wait)').count() === 0, 'verdict: All good, nothing listed to fix');
await p.locator('#checkMore summary').click(); await p.locator('#trackBtn').click(); await p.waitForTimeout(100);
ok(await shelf(p, () => window.__ytCalls.includes('openSettings')), 'YT the settings button opens Shelf\'s iPhone settings');
await p.locator('#ytBtn').click(); await p.waitForTimeout(200);
ok(/Not signed in to YouTube/.test(await p.locator('#checkList').textContent()) && (await p.locator('#ytBtn').textContent()) === 'Sign in to YouTube', 'YT sign out forgets the account');
await ctx.close();
// Google refuses to finish: explained, with the YouTube app as the way to Premium
({ ctx, p } = await appPage({ shell: { ytSignedIn: false, ytRefuse: true } }));
await settle(p);
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
await p.locator('#ytBtn').click(); await p.waitForTimeout(300);
ok(/Google didn't finish signing you in.*YouTube app/.test(await p.locator('#toast').textContent()) && await shelf(p, () => window.__ytCalls.includes('signIn')), 'YT a refused sign-in is explained, no reload');
await ctx.close();
// A shell built before the sign-in plugin
({ ctx, p } = await appPage({ shell: { oldShell: true } }));
await settle(p);
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
ok(/older than the website.*run the installer again/.test(await p.locator('#checkList').textContent()) && !(await p.locator('#ytBtn').isVisible()), 'YT an old shell is told to re-run the installer, no dead button');
await ctx.close();

console.log('\n== Phone storage safety');
const LIBK = 'shelf.v2.library', VK = 'resume.shelf.v1';
const libWith = (extra, rev) => JSON.stringify({ sections: [{ id: 'med', name: 'Medicine', kind: 'video' }, { id: 'ent', name: 'Entertainment', kind: 'video' }, { id: 'sleep', name: 'Sleep', kind: 'audio' }].concat(extra ? [{ id: 'x', name: extra, kind: 'video' }] : []),
  sources: {}, seeded: true, seedV: 2, seedMisses: [], rev: rev });
const phoneSpot = JSON.stringify({ dQw4w9WgXcQ: { id: 'dQw4w9WgXcQ', title: 'Phone spot', t: 600, dur: 1200, updated: Date.now() - 60000 } });
// Phone reads fail: nothing is written to the phone, the self-check says so and offers Try again
({ ctx, p } = await appPage({ prefs: { [VK]: phoneSpot, [LIBK]: libWith('Phone only', 7) }, shell: { prefFail: true } }));
await p.waitForFunction(() => !!window.__shelf, null, { timeout: 12000 }); await p.waitForTimeout(1200);
ok(/didn't answer/.test(await p.locator('#toast').textContent()), 'store: a warning says the phone storage didn\'t answer');
await settle(p);
await shelf(p, () => window.__shelf.handleText('https://youtu.be/swapswapswa')); await p.waitForTimeout(400);
await p.evaluate(() => window.__fake.advance(40)); await p.waitForTimeout(5400);
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(500);
ok(await shelf(p, () => window.__prefWrites) === 0, 'store: with unreadable phone storage nothing is written over it');
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
ok(/didn't answer at start/.test(await p.locator('#checkList').textContent()) && await p.locator('#retryBtn').isVisible(), 'store: self-check explains it and offers Try again');
// The phone answers again: Try again reloads, merges both copies, and only then writes
await p.evaluate(() => localStorage.setItem('fake.prefFail', '0'));
const again = p.waitForEvent('load', { timeout: 5000 }).then(() => true, () => false);
await p.locator('#retryBtn').click();
ok(await again, 'store: Try again restarts Shelf');
await settle(p); await p.waitForTimeout(800);
const merged = await shelf(p, () => ({ v: window.__shelf.videos, phone: JSON.parse(window.__prefs['resume.shelf.v1'] || '{}'), secs: window.__shelf.lib.sections().map((x) => x.name) }));
ok(merged.v.dQw4w9WgXcQ && merged.v.swapswapswa && merged.phone.dQw4w9WgXcQ && merged.phone.swapswapswa, 'store: after Try again the phone keeps its spot and gets the new one');
ok(merged.secs.includes('Phone only'), 'store: the phone\'s newer channel list was kept');
await ctx.close();
// Library: the copy with more saves wins, whichever side it is on
({ ctx, p } = await appPage({ prefs: { [LIBK]: libWith('Phone newer', 9) }, shell: { web: { [LIBK]: libWith('Web older', 4) } } }));
await settle(p); await p.waitForTimeout(600);
let secs = await shelf(p, () => window.__shelf.lib.sections().map((x) => x.name));
ok(secs.includes('Phone newer') && !secs.includes('Web older'), 'store: a newer phone channel list beats a stale web copy (' + secs.join(', ') + ')');
ok(/Phone newer/.test(await shelf(p, () => window.__prefs['shelf.v2.library'])), 'store: and the stale copy is not mirrored over it');
await ctx.close();
({ ctx, p } = await appPage({ prefs: { [LIBK]: libWith('Phone older', 2) }, shell: { web: { [LIBK]: libWith('Web newer', 5) } } }));
await settle(p); await p.waitForTimeout(600);
secs = await shelf(p, () => window.__shelf.lib.sections().map((x) => x.name));
ok(secs.includes('Web newer') && /Web newer/.test(await shelf(p, () => window.__prefs['shelf.v2.library'])), 'store: a newer web copy wins and is backed up to the phone');
await ctx.close();
// Copies from before save counting: the phone's copy is trusted
({ ctx, p } = await appPage({ prefs: { [LIBK]: libWith('Phone legacy') }, shell: { web: { [LIBK]: libWith('Web legacy') } } }));
await settle(p);
secs = await shelf(p, () => window.__shelf.lib.sections().map((x) => x.name));
ok(secs.includes('Phone legacy') && !secs.includes('Web legacy'), 'store: legacy copies (no save count) prefer the phone');
await ctx.close();
// A null entry inside the phone's spots (seen in review) must not stop Home from drawing
({ ctx, p } = await appPage({ prefs: { [VK]: '{"dQw4w9WgXcQ":null}' }, shell: { web: { [VK]: phoneSpot } } }));
await settle(p);
ok(await p.locator('.band').count() >= 3 && await shelf(p, () => !!window.__shelf.videos.dQw4w9WgXcQ), 'store: a null record on the phone is skipped and Home still draws');
await ctx.close();
// A damaged phone record is ignored, the rest still restores
({ ctx, p } = await appPage({ prefs: { [VK]: '{broken', [LIBK]: libWith('Phone ok', 3) } }));
await settle(p); await p.waitForTimeout(600);
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
ok(await shelf(p, () => window.__shelf.lib.sections().some((x) => x.name === 'Phone ok')) && !/didn't answer/.test(await p.locator('#checkList').textContent()), 'store: a damaged phone record is skipped and the rest restores');
await ctx.close();

// Problems are explained in plain words
({ ctx, p } = await appPage({ fakes: { ytDown: true } }));
await p.waitForTimeout(13000);
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
ok((await p.locator('#checkList').textContent()).includes("Can't reach YouTube"), '8 YouTube blocked is explained');
await p.keyboard.press('Escape');
await shelf(p, () => window.__shelf.handleText('https://youtu.be/dQw4w9WgXcQ'));
ok(await p.locator('#perr').isVisible() && (await p.locator('#perr').textContent()).includes('Open on YouTube'), '8 playing then offers Open on YouTube');
await ctx.close();
({ ctx, p } = await appPage());
await settle(p);
await ctx.route('https://www.youtube.com/feeds/**', (r) => r.abort());
await ctx.route('https://www.youtube.com/channel/**', (r) => r.abort());
await shelf(p, () => window.__shelf.refreshAll(true)); await settle(p);
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
const ft = await p.locator('#checkList').textContent();
ok(/Couldn't update .*Dirty Medicine/.test(ft) && await p.locator('#statusDot.bad').count() === 1, '8 channel update failures name the channels');
await p.keyboard.press('Escape');
await shelf(p, () => window.__shelf.handleText('https://youtu.be/blockedxxxx')); await p.waitForTimeout(300);
ok((await p.locator('#perr').textContent()).includes('only lets it play on YouTube'), 'embed-blocked video explained, with Open on YouTube');
await ctx.close();

// Small phone (iPhone SE): player controls and dialog buttons stay reachable
({ ctx, p } = await appPage({ ctxOpts: { viewport: { width: 375, height: 667 } } }));
await settle(p);
await shelf(p, () => window.__shelf.handleText('https://youtu.be/dQw4w9WgXcQ')); await p.waitForTimeout(500);
const ctlBox = await p.locator('#vsheet .ctl').boundingBox();
ok(ctlBox && ctlBox.y + ctlBox.height <= 667 + 1, 'SE: pause button visible without scrolling (bottom ' + (ctlBox && Math.round(ctlBox.y + ctlBox.height)) + ')');
// Turned sideways, the video fills the screen; upright again, the player is back
await p.setViewportSize({ width: 667, height: 375 }); await p.waitForTimeout(150);
const land = await p.locator('#vsheet .vid').boundingBox();
ok(land && land.x === 0 && land.y === 0 && land.width === 667 && land.height === 375, 'sideways: the video fills the screen (' + (land && [land.width, land.height].join('x')) + ')');
await p.setViewportSize({ width: 375, height: 667 }); await p.waitForTimeout(150);
const up = await p.locator('#vsheet .vid').boundingBox();
ok(up && Math.round(up.height) === Math.round(375 * 9 / 16) && await p.locator('#vsheet .ctl').isVisible(), 'upright again: normal player');
await p.locator('[data-act="close-video"]').click();
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
await p.locator('#checkMore summary').click(); await p.locator('#sendBtn').scrollIntoViewIfNeeded();
const sb = await p.locator('#sendBtn').boundingBox();
ok(sb && sb.y + sb.height <= 667, 'SE: self-check buttons reachable');
await ctx.close();


console.log('\n== Courses (Mehlman playlists)');
({ ctx, p } = await appPage({ ctxOpts: { permissions: ['clipboard-read', 'clipboard-write'] } }));
await settle(p);
const cinfo = await shelf(p, () => window.__shelf.courses.list().map((c) => { const pr = window.__shelf.courses.progress(c.id); return c.name + ':' + pr.done + '/' + pr.total + ':' + pr.state; }));
ok(cinfo.join(' ') === 'Paeds:91/130:go OBGYN:60/60:done Ophthal:12/12:done Internal Med:0/150:new Pharm:0/80:new Family Med:0/40:new', 'C six playlists found and ticked from Mo\'s note: ' + cinfo.join(' '));
ok(await shelf(p, () => window.__httpCalls.some((c) => c.method === 'POST' && /youtubei\/v1\/browse/.test(c.url))), 'C long playlists load past the first 100 (native POST)');
ok(await shelf(p, () => { const c = window.__shelf.courses, ob = c.list()[1], pid = Object.keys(ob.pins)[0]; return c.items(ob.id).find((x) => x.id === pid).n; }) === 1607, 'C OBGYN 1607 carries the ‼ pin');
ok(await p.locator('#next').isVisible() && /Paeds · 92 of 130/.test(await p.locator('#nextK').textContent()) && /1115/.test(await p.locator('#nextT').textContent()), 'C Home\'s Up next: ' + await p.locator('#nextK').textContent() + ' · ' + await p.locator('#nextT').textContent());
ok(await p.locator('.band.c1 .sub').count() === 0, 'C Medicine has no exam line on Home');
await p.locator('#coursesBtn').click(); await p.waitForTimeout(150);
ok(await p.locator('#coursesBtn[aria-current="page"]').count() === 1 && await p.locator('#todayBtn[aria-current]').count() === 0, 'tabs: Courses is the current tab');
ok(await p.locator('#page .course').count() === 6, 'C Courses page lists all six');
await p.locator('#page .course .cr').first().click(); await p.waitForTimeout(150);
ok(await p.locator('.course.open .epr').count() === 6 && (await p.locator('.course.open .epr.n').textContent()).includes('1115'), 'C expands to a short window around where you are (' + await p.locator('.course.open .epr').count() + ' rows)');
const rowTxt = (await p.locator('.course.open .epr.n').innerText()).replace(/\s+/g, ' ').trim();
ok(rowTxt === '1115 12:20', 'C a row says its number once, not "1115 HY USMLE Q #1115 - Pediatrics": ' + rowTxt);
await p.locator('.course.open .epr.n .tk').click(); await p.waitForTimeout(150);
ok(/92\/130/.test(await p.locator('.course.open .cn').textContent()), 'C tapping a tick ticks it');
await p.locator('.course.open [data-act="course-later"]').click(); await p.waitForTimeout(100);
ok(await p.locator('.course.open .epr').count() === 16, 'C "more" reveals 10 more, not the whole list');
// hold a later tick: everything above it is ticked, with Undo
const tk = p.locator('.course.open .epr .tk').nth(10); await tk.evaluate((e) => e.scrollIntoView({ block: 'center' })); const tb = await tk.boundingBox();
await p.mouse.move(tb.x + 10, tb.y + 10); await p.mouse.down(); await p.waitForTimeout(700); await p.mouse.up(); await p.waitForTimeout(200);
const afterHold = await shelf(p, () => window.__shelf.courses.progress('PLpeds0000000000').done);
ok(afterHold === 101 && /Ticked everything up to/.test(await p.locator('#toast').textContent()), 'C hold ticks everything up to it (' + afterHold + ')');
await p.locator('#toast button').click(); await p.waitForTimeout(150);
ok(await shelf(p, () => window.__shelf.courses.progress('PLpeds0000000000').done) === 92, 'C Undo puts it back');
// set place by episode number
await p.locator('.course.open [data-act="course-place"]').click(); await p.waitForTimeout(100);
await p.fill('#pl-PLpeds0000000000', '1203'); await p.press('#pl-PLpeds0000000000', 'Enter'); await p.waitForTimeout(150);
ok(await shelf(p, () => window.__shelf.courses.progress('PLpeds0000000000').done) === 103 && /1203 is 103 of 130. Ticked everything up to it/.test(await p.locator('#toast').textContent()), 'C Set place 1203 ticks down to it in playlist order');
// play next from the row, finish it, Next up
await p.locator('.course.open .cgo').click(); await p.waitForTimeout(500);
ok(/PAEDS · 104 OF 130/i.test(await p.locator('#vCh').textContent()), 'C player says which course and where: ' + await p.locator('#vCh').textContent());
ok(await p.locator('#vCourse').isVisible(), 'C player shows the course ruler');
ok(await p.locator('#vNextBtn').isVisible() && /Next: /.test(await p.locator('#vNextBtn').textContent()), 'C player offers the next one beside Mark: ' + await p.locator('#vNextBtn').textContent());
const firstId = await shelf(p, () => window.__shelf.current);
await p.evaluate(() => window.__fake.seekTo(600)); await p.waitForTimeout(300);
ok(await p.locator('#vNext').isVisible() && /Next up/i.test(await p.locator('#vNext').textContent()) && /Plays in/.test(await p.locator('#vNext').textContent()) && await shelf(p, () => window.__shelf.courses.isDone('PLpeds0000000000', window.__shelf.current)), 'C finishing ticks it and counts down to the next one');
await p.locator('#vNext [data-act="ep-play"]').click(); await p.waitForTimeout(400);
ok(await shelf(p, () => window.__shelf.current) !== firstId && /105 OF 130/i.test(await p.locator('#vCh').textContent()), 'C Play next plays the next episode');
await p.locator('.sh-top [data-act="close-video"]').click(); await p.waitForTimeout(200);
ok(await p.locator('#page .cgroup').count() === 3 && await p.locator('#page .subh').count() === 0 && await p.locator('#page .exam').count() === 0, 'C Courses page: one list (on the go, not started, done), no headings, no numbers block');
const cx0 = await p.locator('#page .course:not(.open) .cx').first().textContent();
ok(/^(\d+ left|\d+ videos( · \d+ h)?|Done)$/.test(cx0), 'C closed rows say only what is left: ' + cx0);
const days = await shelf(p, () => window.__shelf.courses.daysLeft());
ok((await p.locator('[data-act="open-pace"]').textContent()).includes(days + ' days to Step 2 CK'), 'C one Pace line on Courses');
await p.locator('[data-act="open-pace"]').click(); await p.waitForTimeout(150);
const ex = await p.locator('#paceBody').textContent();
ok(ex.includes(String(days)) && /Today 2/.test(ex) && /PAEDS|Paeds/.test(ex) && /26 left/.test(ex), 'C Pace sheet: ' + days + ' days, today 2, Paeds 26 left (' + ex.replace(/\s+/g, ' ').slice(0, 90) + ')');
await p.locator('#paceCopy').click(); await p.waitForTimeout(300);
const plan = (await shelf(p, () => window.__clip)) || await p.evaluate(() => navigator.clipboard.readText().catch(() => ''));
ok(/Goal: Step 2 CK on 22 December 2026, \d+ days from today/.test(plan) && /Paeds( \([^)]*\))?: 104 of 130 watched, 26 left/.test(plan) && /how many videos a day/.test(plan), 'C Copy for Claude gives a plan question: ' + JSON.stringify(plan.split('\n').slice(1, 4)));
await p.keyboard.press('Escape');
// Edit the goal from the Pace sheet: name and date, then back to Step 2 CK
await p.locator('[data-act="open-pace"]').click(); await p.waitForTimeout(150);
ok(/Goal\s*Step 2 CK · 22 Dec/.test(await p.locator('#paceBody .goal').textContent()), 'G the Pace sheet starts with the goal: ' + await p.locator('#paceBody .goal').textContent());
await p.locator('#paceBody .goal').click(); await p.waitForTimeout(150);
ok(await p.locator('#goalDlg[open]').count() === 1 && await p.inputValue('#goalName') === 'Step 2 CK' && await p.inputValue('#goalDate') === '2026-12-22', 'G Edit opens the goal form filled in');
await p.fill('#goalName', ''); await p.locator('#goalForm button[type="submit"]').click(); await p.waitForTimeout(100);
ok(/Give it a name/.test(await p.locator('#goalMsg').textContent()) && await p.locator('#goalDlg[open]').count() === 1, 'G an empty name says what to do');
const gd = await p.evaluate(() => { const d = new Date(); d.setDate(d.getDate() + 20); return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0'); });
await p.fill('#goalName', 'Paeds shelf'); await p.fill('#goalDate', '2026-01-02'); await p.locator('#goalForm button[type="submit"]').click(); await p.waitForTimeout(100);
ok(/has passed/.test(await p.locator('#goalMsg').textContent()), 'G a past date is refused');
await p.fill('#goalName', 'Paeds shelf'); await p.fill('#goalDate', gd); await p.locator('#goalForm button[type="submit"]').click(); await p.waitForTimeout(250);
ok(await p.locator('#paceDlg[open]').count() === 1 && /Paeds shelf/.test(await p.locator('#paceBody .goal').textContent()) && /20 days to Paeds shelf/.test(await p.locator('#toast').textContent()), 'G saving shows the new goal: ' + await p.locator('#toast').textContent());
ok(await shelf(p, () => window.__shelf.courses.daysLeft()) === 20 && await shelf(p, () => window.__shelf.prefs.goal.name) === 'Paeds shelf', 'G days left and per-day pace follow the new date');
await p.keyboard.press('Escape'); await p.waitForTimeout(100);
ok((await p.locator('[data-act="open-pace"]').textContent()).includes('20 days to Paeds shelf'), 'G the Pace line names the new goal');
await p.reload(); await settle(p); await p.locator('#coursesBtn').click(); await p.waitForTimeout(200);
ok((await p.locator('[data-act="open-pace"]').textContent()).includes('20 days to Paeds shelf'), 'G the goal survives a relaunch');
await p.locator('[data-act="open-pace"]').click(); await p.waitForTimeout(150);
await p.locator('#paceBody .goal').click(); await p.waitForTimeout(150);
await p.locator('#goalDlg [data-act="goal-reset"]').click(); await p.waitForTimeout(150);
ok(await p.locator('#paceDlg[open]').count() === 1 && await shelf(p, () => !window.__shelf.prefs.goal), 'G reset goes back to the Pace sheet');
await p.keyboard.press('Escape'); await p.waitForTimeout(100);
ok((await p.locator('[data-act="open-pace"]').textContent()).includes(days + ' days to Step 2 CK') && await shelf(p, () => !window.__shelf.prefs.goal), 'G reset puts back Step 2 CK');
await p.locator('#page .top [data-act="add-course"]').click(); await p.waitForTimeout(500);
await p.fill('#courseInput', 'surg'); await p.waitForTimeout(150);
ok(await p.locator('#coursePicks [data-pl]').count() === 1, 'C typing finds Mehlman\'s Surgery playlist');
await p.locator('#coursePicks [data-pl]').click(); await p.locator('#courseGo').click(); await p.waitForTimeout(600);
ok(/Added Surgery · 25 videos/.test(await p.locator('#courseMsg').textContent()), 'C added: ' + await p.locator('#courseMsg').textContent());
await p.waitForTimeout(1000);
ok(await p.locator('#courseDlg[open]').count() === 0 && await p.evaluate(() => document.activeElement && document.activeElement.id === 'pl-PLsurg0000000000'), 'C after adding, it asks where you\'ve watched up to');
ok(/Watched up to/.test(await p.locator('.course.open .cplace label').textContent()) && await p.locator('.course.open .cplace', { hasText: 'Not started' }).count() === 1, 'C the place form offers Not started');
await p.fill('#pl-PLsurg0000000000', '5'); await p.press('#pl-PLsurg0000000000', 'Enter'); await p.waitForTimeout(150);
ok(await shelf(p, () => window.__shelf.courses.progress('PLsurg0000000000').done) === 0 && /No episode 5 in Surgery. Meant the first 5 videos/.test(await p.locator('#toast').textContent()), 'C numbered titles with no episode 5 ask first: ' + await p.locator('#toast').textContent());
await p.locator('#toast button').click(); await p.waitForTimeout(150);
ok(await shelf(p, () => window.__shelf.courses.progress('PLsurg0000000000').done) === 5 && /Video 5 of 25/.test(await p.locator('#toast').textContent()), 'C Tick 5 ticks the first 5 videos: ' + await p.locator('#toast').textContent());
await p.locator('#searchBtn').click(); await p.fill('#sq', 'https://www.youtube.com/playlist?list=PLs1pharm0000000'); await p.press('#sq', 'Enter'); await p.waitForTimeout(300);
ok(await p.locator('#courseDlg[open]').count() === 1 && (await p.inputValue('#courseInput')).includes('PLs1pharm'), 'C a playlist link in Search opens Add course');
await p.keyboard.press('Escape');
// Watched the newest Internal Med video first (the last in its playlist): still draws, next is the first gap
await shelf(p, () => { const c = window.__shelf.courses, it = c.items('PLim000000000000'); c.tick('PLim000000000000', it[it.length - 1].id, true); });
await p.locator('#coursesBtn').click(); await p.waitForTimeout(200);
await p.locator('#page .course', { hasText: 'Internal Med' }).locator('.cr').click(); await p.waitForTimeout(150);
ok(/Next · 100 /.test((await p.locator('#page .course', { hasText: 'Internal Med' }).locator('.cx').allTextContents()).join(' ')), 'C last video ticked first: next is the first one still open');
await p.locator('#todayBtn').click(); await p.waitForTimeout(150);
ok(await p.locator('#todayBtn[aria-current="page"]').count() === 1 && await p.locator('#home').isVisible(), 'tabs: Today goes back to Home');
// A Mehlman playlist that wasn't found: a quiet Add playlist line on Courses, never a problem in the self-check
await shelf(p, () => { window.__shelf.courses.raw().misses = [{ name: 'Family Med', error: 'not on the channel' }]; });
await p.locator('#coursesBtn').click(); await p.waitForTimeout(200);
ok(await p.locator('#page .more.quiet', { hasText: 'Family Med · not found' }).count() === 1, 'C a playlist not found is one quiet + Add playlist line');
await p.locator('#todayBtn').click(); await p.waitForTimeout(150);
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
ok(!/Family Med/.test(await p.locator('#checkDlg').textContent()), 'C the self-check doesn\'t nag about it');
ok(/Tracking 7 courses/.test(await p.locator('#checkList').textContent()), 'C self-check counts the courses');
await p.keyboard.press('Escape');
ok(await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'C no sideways scroll');
await p.waitForTimeout(500);
const cprefs = await shelf(p, () => window.__prefs);
await ctx.close();
// ticks survive a relaunch (phone storage only)
({ ctx, p } = await appPage({ prefs: cprefs }));
await settle(p);
const kept = await shelf(p, () => window.__shelf.courses.progress('PLpeds0000000000').done); ok(kept === 104, 'C ticks kept after closing the app (' + kept + ')');
await ctx.close();
// YouTube refuses the playlist: explained, ticks kept
({ ctx, p } = await appPage({ prefs: cprefs, fakes: { plDown: true } }));
await settle(p);
await shelf(p, () => window.__shelf.courses.load('PLpeds0000000000', true)); await p.waitForTimeout(100);
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
ok(/Couldn't load Paeds/.test(await p.locator('#checkList').textContent()), 'C a playlist that won\'t load is named in the self-check');
await ctx.close();
// iPhone SE: the open course fits
({ ctx, p } = await appPage({ ctxOpts: { viewport: { width: 375, height: 667 } } }));
await settle(p);
await p.locator('#coursesBtn').click(); await p.locator('#page .course .cr').first().click(); await p.waitForTimeout(150);
ok(await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'SE: open course has no sideways scroll');
await ctx.close();

console.log('\n== Player: swipe, speed per channel, Mark');
({ ctx, p } = await appPage({ ctxOpts: { permissions: ['clipboard-read', 'clipboard-write'] } }));
await settle(p);
await p.locator('#searchBtn').click(); await p.fill('#sq', 'hypokalemia');
await shelf(p, () => window.__shelf.refreshAll(true)); await settle(p); await p.waitForTimeout(200);
ok(await p.inputValue('#sq') === 'hypokalemia', 'search: what you typed survives a background refresh');
await p.press('#sq', 'Enter'); await p.waitForTimeout(400);
ok(await p.locator('#vsheet.open').count() === 0 && await shelf(p, () => !window.__shelf.videos.hypokalemia), 'search: an 11-letter word is searched, not played as a video id');
// tabs take their pages' history with them: Medicine › channel › Courses leaves one page behind Home, not three
await p.locator('#todayBtn').click(); await p.waitForTimeout(300);
const h0 = await p.evaluate(() => history.length);
await p.locator('.band.c1 .hd .tm').click(); await p.locator('#page details.fold summary', { hasText: 'Channels' }).click(); await p.locator('#page .chrow').first().click(); await p.locator('#coursesBtn').click(); await p.waitForTimeout(400);
ok(await p.evaluate(() => history.length) <= h0 + 1 && await shelf(p, () => window.__shelf.stack.length) === 1, 'tabs: switching tabs doesn\'t pile up Back steps');
await p.goBack(); await p.waitForTimeout(300);
ok(await p.locator('#page').isHidden(), 'tabs: Back from a tab goes Home');
const playFrom = async (sec, chan, title) => {
  await p.locator('#todayBtn').click(); await p.waitForTimeout(100);
  await p.locator('.band', { hasText: sec }).locator('.hd .tm').first().click();
  const fs = p.locator('#page details.fold:not([open]) summary', { hasText: 'Channels' }); if (await fs.count()) await fs.click();
  await p.locator('#page .chrow', { hasText: chan }).click();
  await p.locator('#page .item', { hasText: title }).first().click(); await p.waitForTimeout(700);
};
await playFrom('Medicine', 'Mehlman Medical', 'Renal');
// swipe down on the top bar: a short pull springs back, a long one closes
const drag = async (dist) => { const bx = await p.locator('#vsheet .sh-top').boundingBox(); const x = bx.x + bx.width / 2, y = bx.y + bx.height / 2;
  await p.mouse.move(x, y); await p.mouse.down(); for (let i = 1; i <= dist / 10; i++) { await p.mouse.move(x, y + i * 10); await p.waitForTimeout(30); } await p.mouse.up(); await p.waitForTimeout(400); };
await drag(60);
ok(await p.locator('#vsheet.open').count() === 1, 'swipe: a short pull springs back');
await drag(160);
ok(await p.locator('#vsheet.open').count() === 0, 'swipe: pulling the player down closes it');
await p.locator('#page .item', { hasText: 'Renal' }).first().click(); await p.waitForTimeout(700);
await p.locator('#vRate [data-r="1.5"]').click(); await p.waitForTimeout(200);
ok(await shelf(p, () => window.__fake.getPlaybackRate()) === 1.5 && await shelf(p, () => window.__shelf.prefs.rates['v:UCMehlmanMedicalxxxxxxxx']) === 1.5, 'speed: 1.5× saved for Mehlman Medical');
await p.evaluate(() => window.__fake.advance(150)); await p.waitForTimeout(1300);
await p.locator('#vMark').click(); await p.waitForTimeout(200);
ok(await shelf(p, () => window.__shelf.marks.count) === 1 && /Marked 2:\d\d/.test(await p.locator('#toast').textContent()), 'mark: one tap marks the spot: ' + await p.locator('#toast').textContent());
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(200);
await p.locator('#page .item', { hasText: 'Endocrine' }).first().click(); await p.waitForTimeout(3200);
ok(await shelf(p, () => window.__fake.getPlaybackRate()) === 1.5, 'speed: another Mehlman video starts at 1.5×');
await p.locator('[data-act="close-video"]').first().click();
await playFrom('Entertainment', 'Breaking Points', 'Fed Cuts');
await p.waitForTimeout(2600);
ok(await shelf(p, () => window.__fake.getPlaybackRate()) === 1 && await p.locator('#vRate [data-r="1"][aria-pressed="true"]').count() === 1, 'speed: Breaking Points stays at 1×');
await p.locator('[data-act="close-video"]').first().click();
await p.reload(); await settle(p);
await playFrom('Medicine', 'Mehlman Medical', 'Psychiatry');
await p.waitForTimeout(2600);
ok(await shelf(p, () => window.__fake.getPlaybackRate()) === 1.5, 'speed: remembered after closing the app');
await p.locator('[data-act="close-video"]').first().click();
await p.locator('#todayBtn').click(); await p.locator('.band.c1 .hd .tm').click();
await p.locator('#page .top [data-act="open-marks"]').click(); await p.waitForTimeout(150);
ok(await p.locator('#page .mrow').count() === 1 && /Renal/.test(await p.locator('#page .mrow').textContent()), 'mark: the Marks page lists it');
await p.locator('[data-act="marks-copy"]').click(); await p.waitForTimeout(300);
const anki = (await shelf(p, () => window.__clip)) || await p.evaluate(() => navigator.clipboard.readText().catch(() => ''));
ok(/Renal.*@ 2:\d\d.*\t.*youtube.*t=\d+s/.test(anki), 'mark: Copy for Anki gives tab-separated cards: ' + JSON.stringify(anki).slice(0, 90));
const rid = await shelf(p, () => window.__shelf.marks.list()[0].vid), mt = await shelf(p, () => window.__shelf.marks.list()[0].t);
await shelf(p, () => { const v = Object.values(window.__shelf.videos).find((x) => /Renal/.test(x.title)); v.t = 400; });
await p.locator('#page [data-act="mark-play"]').first().click(); await p.waitForTimeout(600);
ok(Math.abs(await shelf(p, () => window.__lastStart) - mt) < 2 && await p.evaluate((id) => window.__shelf.videos[id].t, rid) >= 399, 'mark: playing a mark starts there without moving the saved spot (' + JSON.stringify([mt, await shelf(p, () => window.__lastStart), await p.evaluate((id) => window.__shelf.videos[id] && window.__shelf.videos[id].t, rid), rid]) + ')');
await p.locator('[data-act="close-video"]').first().click();
await shelf(p, () => { window.__shelf.prefs.rate = 1.25; });
await playFrom('Entertainment', 'Breaking Points', 'Shutdown'); await p.waitForTimeout(2600);
ok(await shelf(p, () => window.__fake.getPlaybackRate()) === 1.25, 'speed: a speed saved by the old version still applies');
await p.locator('[data-act="close-video"]').first().click();
await ctx.close();

console.log('\n== D Day or night (light from an hour after sunrise, dark from an hour before sunset)');
// The iPhone itself is in dark mode; it's 1 pm in London, when the sun is up all year
({ ctx, p } = await appPage({ fakes: { fresh: false }, shell: { hour: 13 }, ctxOpts: { colorScheme: 'dark' } }));
await settle(p);
const bg = () => p.evaluate(() => getComputedStyle(document.body).backgroundColor);
ok(await p.evaluate(() => document.documentElement.getAttribute('data-theme')) === 'light' && await bg() === 'rgb(255, 255, 255)', 'D 1 pm: Shelf is light even with the iPhone in dark mode (' + await bg() + ')');
const strip = () => p.evaluate(() => { const c = getComputedStyle(document.documentElement, '::before'); return c.content === 'none' ? 'none' : c.backgroundColor; });
ok(await strip() === 'rgb(12, 12, 16)', 'D the strip under the clock stays dark, so the iPhone\'s white clock stays readable (' + await strip() + ')');
ok(await p.locator('#lookBtn svg circle').count() === 1, 'D the top shows a sun');
ok(await p.evaluate(() => JSON.parse(localStorage.getItem('shelf.look')).u > Date.now()), 'D the look is kept for the next launch with the time it changes');
await p.locator('#lookBtn').click(); await p.waitForTimeout(150);
ok(!(await p.locator('#lookDlg [data-act="look-here"]').isVisible()), 'D in this app build Use my location is hidden (it has no location permission yet)');
const when = await p.locator('#lookWhen').textContent();
ok(await p.locator('#lookDlg[open]').count() === 1 && /^Light until \d{1,2}:\d\d pm, then dark\.$/.test(when) && /Sun times for London/.test(await p.locator('#lookWhere').textContent()), 'D the sun sheet says when it turns dark: ' + when);
ok(await p.locator('#lookPicks [data-id="auto"][aria-pressed="true"]').count() === 1, 'D Auto is picked');
await p.locator('#lookPicks [data-id="dark"]').click(); await p.waitForTimeout(100);
ok(await p.evaluate(() => document.documentElement.getAttribute('data-theme')) === 'dark' && await bg() === 'rgb(10, 10, 14)' && /^Dark all the time/.test(await p.locator('#lookWhen').textContent()), 'D Dark switches at once');
await p.reload(); await settle(p);
ok(await p.evaluate(() => document.documentElement.getAttribute('data-theme')) === 'dark' && await shelf(p, () => window.__shelf.prefs.look) === 'dark', 'D Dark is remembered');
await p.locator('#lookBtn').click(); await p.locator('#lookPicks [data-id="auto"]').click(); await p.waitForTimeout(100);
ok(await p.evaluate(() => document.documentElement.getAttribute('data-theme')) === 'light', 'D Auto goes back to the sun (light at 1 pm)');
// Typing a town: British places first (there is a Leeds in Alabama too)
await p.locator('#lookDlg details summary').click(); await p.fill('#lookTown', 'Leeds'); await p.locator('#lookForm button[type="submit"]').click(); await p.waitForTimeout(400);
const loc = await shelf(p, () => window.__shelf.prefs.loc);
ok(loc && loc.name === 'Leeds' && Math.abs(loc.lat - 53.8) < 0.01 && Math.abs(loc.lon + 1.55) < 0.01 && /Using Leeds, England/.test(await p.locator('#lookMsg').textContent()) && /Sun times for Leeds/.test(await p.locator('#lookWhere').textContent()), 'D typing Leeds uses Leeds in England: ' + JSON.stringify(loc));
await p.fill('#lookTown', 'Nowhereville'); await p.locator('#lookForm button[type="submit"]').click(); await p.waitForTimeout(300);
ok(/No town called "Nowhereville"/.test(await p.locator('#lookMsg').textContent()) && (await shelf(p, () => window.__shelf.prefs.loc.name)) === 'Leeds', 'D an unknown town says so and keeps Leeds');
await p.keyboard.press('Escape');
// Evening comes: it turns dark by itself, without reopening
await p.evaluate(() => { window.__hour = 22; window.__shelf.applyLook(); }); await p.waitForTimeout(100);
ok(await p.evaluate(() => document.documentElement.getAttribute('data-theme')) === 'dark' && await p.locator('#lookBtn svg circle').count() === 0 && await strip() === 'none', 'D at 10 pm it is dark by itself, with a moon, and no strip is needed');
await p.locator('#lookBtn').click(); await p.waitForTimeout(100);
ok(/^Dark until \d{1,2}:\d\d am tomorrow, then light\.$/.test(await p.locator('#lookWhen').textContent()), 'D at night it says when it turns light: ' + await p.locator('#lookWhen').textContent());
await p.keyboard.press('Escape');
ok((await shelf(p, () => window.__shelf.checks().map((c) => c.text).join('|'))).includes('Look: dark by the sun, using Leeds\'s sun times'), 'D the self-check names the look and the town');
// A goal saved with the old 30 Nov date moves to 22 Dec
await p.evaluate(() => { const k = 'resume.prefs.v1', v = JSON.parse(localStorage.getItem(k) || '{}'); v.goal = { name: 'Step 2 CK', date: '2026-11-30' }; localStorage.setItem(k, JSON.stringify(v)); });
await p.reload(); await settle(p);
ok(await shelf(p, () => window.__shelf.prefs.goal.date) === '2026-12-22' && await shelf(p, () => window.__shelf.courses.daysLeft()) === Math.round((new Date(2026, 11, 22) - new Date(new Date().toDateString())) / 864e5), 'D an old Step 2 CK goal on 30 Nov becomes 22 Dec');
await ctx.close();

console.log('\n== P Polish: a broken duplicate channel');
({ ctx, p } = await appPage({ fakes: { fresh: false } }));
await settle(p);
// A second "The Ezra Klein Show" that never loads (Mo has one)
await p.evaluate(() => { const k = 'shelf.v2.library', v = JSON.parse(localStorage.getItem(k)); const ez = Object.values(v.sources).find((s) => s.name === 'The Ezra Klein Show'); v.sources.UCbrokenCopy0000000000xx = Object.assign({}, ez, { id: 'UCbrokenCopy0000000000xx' }); localStorage.setItem(k, JSON.stringify(v)); });
await p.reload(); await settle(p); await shelf(p, () => window.__shelf.refreshAll(true)); await settle(p);
ok(await shelf(p, () => !window.__shelf.lib.status('UCbrokenCopy0000000000xx').ok), 'P the copy fails to load');
await p.locator('.band.c2 .tg').click(); await p.waitForTimeout(100);
ok(await p.locator('.band.c2 .chl button', { hasText: 'The Ezra Klein Show' }).count() === 1 && !/Couldn't update/.test(await p.locator('.band.c2').textContent()), 'P Home lists Ezra once, with no "Couldn\'t update"');
ok(!(await shelf(p, () => window.__shelf.checks().map((c) => c.text).join('|'))).includes("Couldn't update"), 'P the self-check doesn\'t nag about it');
await p.locator('.band.c2 .hd .tm').click(); await p.locator('#page details.fold summary', { hasText: 'Channels' }).click();
const rd = p.locator('#page [data-act="remove-dup"]');
ok(await rd.count() === 1 && /in here twice/.test(await rd.textContent()), 'P the section page offers to remove the broken copy');
await rd.click(); await p.waitForTimeout(100);
ok(/Tap again/.test(await p.locator('#page [data-act="remove-dup"]').textContent()), 'P one tap asks for a second');
await p.locator('#page [data-act="remove-dup"]').click(); await p.waitForTimeout(150);
ok(await shelf(p, () => !window.__shelf.lib.source('UCbrokenCopy0000000000xx') && window.__shelf.lib.sources().filter((s) => s.name === 'The Ezra Klein Show').length === 1), 'P the second tap removes only the broken copy');
await ctx.close();

console.log('\n== Night (23:12)');
({ ctx, p } = await appPage({ fakes: { fresh: false }, shell: { hour: 23.2 } }));
await settle(p);
ok((await p.locator('.band .hd h2').allTextContents()).join(',') === 'Entertainment,Medicine,Sleep,Pasted' && /night/.test(await p.locator('#dayName').textContent()), 'night: the same fixed order (Mo\'s), the Bedtime card leads instead');
await p.locator('.band.c3 .hd .tm').click();
await p.locator('#page .item', { hasText: 'Rome' }).click(); await p.waitForTimeout(1200);
const tmr = await p.evaluate(() => { const t = window.__shelf.engine.state().timer; return t && Math.round((t.endsAt - Date.now()) / 60000); });
ok(tmr === 45 && /45-minute sleep timer on/.test(await p.locator('#toast').textContent()), 'night: a 45-minute sleep timer starts by itself (' + tmr + ' min)');
await p.locator('#nSeg [data-m="45"]').click(); await p.locator('[data-act="close-night"]').click(); await p.waitForTimeout(200);
await p.locator('#page .item', { hasText: 'Rome' }).click(); await p.waitForTimeout(600);
ok(await p.evaluate(() => !window.__shelf.engine.state().timer), 'night: a timer you turned off stays off when you reopen the episode');
await p.evaluate(() => { document.querySelector('#audio').currentTime = 60; }); await p.waitForTimeout(600);
await p.evaluate(() => { document.querySelector('#audio').pause(); window.__shelf.engine.capture(true); }); await p.waitForTimeout(200);
await p.locator('[data-act="close-night"]').click(); await p.locator('#todayBtn').click(); await p.waitForTimeout(300);
ok(await p.locator('#mini').isVisible() && !(await p.locator('#cont').isVisible() && /Rome/.test(await p.locator('#contTitle').textContent())), 'night: while the podcast bar holds it, no second Bedtime card');
await p.waitForTimeout(5200); await p.reload(); await settle(p); await p.waitForTimeout(300);
ok((await p.locator('#contK').textContent()).startsWith('Bedtime') && /lights out/.test(await p.locator('#contMeta').textContent()), 'night: the Bedtime card offers the podcast: ' + await p.locator('#contMeta').textContent());
ok(!(await p.locator('#next').isVisible()), 'night: no Up next lecture at bedtime');
await ctx.close();

console.log('\n== G Gemini');
const G = { mode: 'ok', calls: [] }, GKEY = 'AIzaGEMINIFAKEKEY0000000000000001';
({ ctx, p } = await appPage({ prefs: { 'gemini.key': GKEY }, fakes: { fresh: true, gemini: G }, ctxOpts: { permissions: ['clipboard-read', 'clipboard-write'] } }));
const clipNow = async () => (await p.evaluate(() => navigator.clipboard.readText().catch(() => ''))) || await shelf(p, () => window.__clip);
await settle(p);
await p.waitForFunction(() => window.__shelf.checks().some((c) => /^Gemini: working/.test(c.text)), null, { timeout: 5000 }).catch(() => {});
const gRow = async () => (await shelf(p, () => window.__shelf.checks().map((c) => c.text))).find((t) => /Gemini/.test(t)) || '';
ok(/^Gemini: working · [\d.]+ of 8 video hours used today$/.test(await gRow()) && (await shelf(p, () => window.__httpCalls)).some((c) => /generativelanguage/.test(c.url) && c.headers['x-goog-api-key'] === 'AIzaGEMINIFAKEKEY0000000000000001' && !/key=/.test(c.url)) && G.calls.some((c) => c.text === 'Reply OK'), 'G self-check tests the key with a tiny call: ' + await gRow());
const sumCalls = () => G.calls.filter((c) => /"points"/.test(c.text));
await p.waitForFunction(() => !window.__shelf.ai.busy, null, { timeout: 8000 }).catch(() => {});
const upn = sumCalls().map((c) => c.video.slice(-11));
ok(upn.length === 1 && /^peds/.test(upn[0]), 'G first run: only the course\'s next episode is summarised ahead (nothing is new yet): ' + upn.join(' '));
await shelf(p, () => window.__shelf.refreshAll(true)); await settle(p);
await p.waitForFunction(() => !window.__shelf.ai.busy, null, { timeout: 8000 }).catch(() => {}); await p.waitForTimeout(300);
const medIds = Object.entries(CHANNELS).filter(([h]) => /Dirty|Mehlman|AJs/.test(h)).map(([, c]) => c.id.slice(2, 10));
const sv = sumCalls().slice(1).map((c) => c.video.slice(-11));
ok(sv.length === 3 && sv.every((v) => medIds.some((m) => v.startsWith(m))), 'G new Medicine uploads are summarised by themselves (3), nothing from Entertainment: ' + sv.join(' '));
ok(sumCalls().every((c) => !c.processing && !c.clip), 'G 10-minute videos use Gemini\'s default processing');
ok(/^Gemini: working · 0\.7 of 8 video hours used today$/.test(await gRow()), 'G the self-check counts the hours: ' + await gRow());
// Open one: the folded Summary is ready, its times seek
await playFrom('Medicine', 'Mehlman Medical', 'Renal');
ok(await p.locator('#vAiBtn').isVisible() && /ready/.test(await p.locator('#vAiSt').textContent()) && await p.locator('#vAi').isHidden(), 'G a folded Summary line under the title says ready');
await p.locator('#vAiBtn').click(); await p.waitForTimeout(150);
ok(await p.locator('#vAi .pts li').count() === 3 && /Fake gist/.test(await p.locator('#vAi .gist').textContent()), 'G tapping it shows the gist and 3 points');
await p.locator('#vAi .tt').nth(1).click(); await p.waitForTimeout(300);
ok(Math.abs(await shelf(p, () => window.__fake.getCurrentTime()) - 125) < 2, 'G tapping 2:05 jumps there');
// Notes: Step 2 notes, copy for Anki (tab-separated) and as text
await p.locator('#vNotes').click();
await p.waitForSelector('#notesBody .nts', { timeout: 5000 }).catch(() => {});
const nb = await p.locator('#notesBody').textContent();
ok(/High-yield/.test(nb) && /How it's tested/.test(nb) && /Versus/.test(nb) && /Thiazides/.test(nb), 'G Notes come as Step 2 notes (facts, how it\'s tested, versus)');
ok(G.calls.filter((c) => /"cards"/.test(c.text)).length === 1, 'G notes are one call (the fenced reply is read)');
await p.locator('#notesBody [data-act="notes-anki"]').click(); await p.waitForTimeout(300);
const nclip = await clipNow();
ok(nclip.split('\n').length === 1 && nclip.split('\t').length === 2 && /<b>loop diuretic hypokalaemia<\/b>/.test(nclip) && /Versus thiazides/.test(nclip), 'G Copy for Anki: front TAB back: ' + nclip.slice(0, 80));
await p.locator('#notesBody [data-act="notes-text"]').click(); await p.waitForTimeout(300);
const ntext = await clipNow();
ok(/^# HY Arrows: Renal Physiology/.test(ntext) && /## Versus/.test(ntext), 'G Copy as text gives Markdown');
await p.keyboard.press('Escape'); await p.waitForTimeout(100);
await p.locator('#vNotes').click(); await p.waitForTimeout(300);
ok(G.calls.filter((c) => /"cards"/.test(c.text)).length === 1 && await p.locator('#notesBody .nts').count() === 1, 'G opening Notes again costs nothing (saved)');
await p.keyboard.press('Escape'); await p.waitForTimeout(100);
// Mark: a drafted card from the two minutes around it
await p.evaluate(() => window.__fake.seekTo(252)); await p.waitForTimeout(1200);
await p.locator('#vMark').click(); await p.waitForTimeout(200);
ok(/Marked 4:1\d · drafting a card/.test(await p.locator('#toast').textContent()), 'G Mark says it is drafting a card: ' + await p.locator('#toast').textContent());
await p.locator('#toast button').click(); await p.waitForTimeout(150);
await p.fill('#noteInput', 'Kawasaki: IVIG'); await p.locator('#noteForm button[type="submit"]').click();
await p.waitForFunction(() => /card drafted/.test(document.querySelector('#toast').textContent), null, { timeout: 5000 }).catch(() => {});
const cc = G.calls.filter((c) => /ONE card/.test(c.text));
ok(/Marked 4:1\d · card drafted/.test(await p.locator('#toast').textContent()) && cc.length === 1, 'G the toast says the card is drafted: ' + await p.locator('#toast').textContent());
ok(cc[0] && cc[0].processing === 'STATIC' && /^1[67]\ds$/.test(cc[0].clip.startOffset) && /^2[78]\ds$/.test(cc[0].clip.endOffset) && /Kawasaki: IVIG/.test(cc[0].text), 'G the card is drafted from 90 s before to 30 s after, with the note: ' + JSON.stringify(cc[0] && cc[0].clip));
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(200);
await p.locator('#todayBtn').click(); await p.locator('.band.c1 .hd .tm').click();
await p.locator('#page .top [data-act="open-marks"]').click(); await p.waitForTimeout(150);
ok(await p.locator('#page .mcard summary', { hasText: 'Card drafted' }).count() === 1, 'G the Marks page shows the drafted card, folded');
await p.locator('[data-act="marks-copy"]').click(); await p.waitForTimeout(300);
const mclip = await clipNow();
ok(/Kawasaki disease/.test(mclip) && mclip.split('\t').length === 2 && !/youtube\.com/.test(mclip), 'G Copy for Anki exports the drafted card');
// A video outside Medicine: nothing made ahead; tapping Summary makes one
const before = sumCalls().length;
await playFrom('Entertainment', 'Breaking Points', 'Fed Cuts'); await p.waitForTimeout(300);
ok(/tap to make/.test(await p.locator('#vAiSt').textContent()) && sumCalls().length === before, 'G Breaking Points: no summary made ahead');
G.mode = 'slow';
await p.locator('#vAiBtn').click(); await p.waitForTimeout(400);
ok(/watching/.test(await p.locator('#vAiSt').textContent()) && /Gemini is watching/.test(await p.locator('#vAi').textContent()), 'G while Gemini works it says so');
await p.waitForSelector('#vAi .pts', { timeout: 5000 }).catch(() => {});
ok(await p.locator('#vAi .pts li').count() === 3 && !/Step 2/.test(sumCalls().slice(-1)[0].text), 'G tapping Summary makes one (plain, not Step 2)');
await p.locator('#vNotes').click(); await p.waitForSelector('#notesBody .nts', { timeout: 5000 }).catch(() => {});
ok(/A plain bullet/.test(await p.locator('#notesBody').textContent()) && await p.locator('#notesBody [data-act="notes-anki"]').count() === 0, 'G notes outside Medicine are plain bullets, no Anki cards');
await p.keyboard.press('Escape'); G.mode = 'ok';
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(150);
// Errors in plain words
await shelf(p, () => window.__shelf.handleText('https://youtu.be/privvid0001')); await p.waitForTimeout(500);
await p.locator('#vAiBtn').click(); await p.waitForTimeout(400);
ok(/isn't public/.test(await p.locator('#vAi').textContent()), 'G a private video: ' + await p.locator('#vAi').textContent());
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(150);
await shelf(p, () => window.__shelf.handleText('https://youtu.be/busyvid0001')); await p.waitForTimeout(500);
G.mode = 'busy'; await p.locator('#vAiBtn').click();
await p.waitForFunction(() => /busy/.test(document.querySelector('#vAi').textContent), null, { timeout: 3000 }).catch(() => {});
ok(/Gemini is busy. Trying again in a minute/.test(await p.locator('#vAi').textContent()), 'G 429: busy, trying again');
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(150);
G.mode = 'daily';
await shelf(p, () => window.__shelf.handleText('https://youtu.be/dailyvid001')); await p.waitForTimeout(500);
await p.locator('#vAiBtn').click(); await p.waitForTimeout(500);
ok(/Free video limit used for today. It resets at \d+(am|pm)/.test(await p.locator('#vAi').textContent()), 'G the daily limit: ' + await p.locator('#vAi').textContent());
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(150);
G.mode = 'badkey';
await shelf(p, () => window.__shelf.handleText('https://youtu.be/keyvid00001')); await p.waitForTimeout(500);
await p.locator('#vAiBtn').click(); await p.waitForTimeout(500);
ok(/Google says the key is wrong. Paste it again./.test(await p.locator('#vAi').textContent()), 'G a bad key says so in the player');
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(150);
await p.locator('#todayBtn').click(); await p.waitForTimeout(150);
await p.locator('#statusBtn').click(); await p.waitForTimeout(200);
ok(/Gemini: Google says the key is wrong/.test(await p.locator('#checkProblems').textContent()) && await p.locator('#checkProblems [data-act="ai-key"]').count() === 1, 'G the self-check shows a bad key as a problem, with a fix');
await p.locator('#checkProblems [data-act="ai-key"]').click(); await p.waitForTimeout(150);
await p.locator('#aiKeyDlg [data-act="ai-key-remove"]').click(); await p.waitForTimeout(200);
await p.keyboard.press('Escape'); G.mode = 'ok';
ok(/^No Gemini key yet. Tap to add one.$/.test(await gRow()), 'G with no key: ' + await gRow());
await p.locator('#statusBtn').click(); await p.waitForTimeout(150);
await p.locator('#checkAll summary').click();
await p.locator('#checkList [data-act="ai-key"]').click(); await p.waitForTimeout(150);
await p.fill('#aiKeyInput', 'hello'); await p.locator('#aiKeyForm button[type="submit"]').click(); await p.waitForTimeout(100);
ok(/too short to be a key/.test(await p.locator('#aiKeyMsg').textContent()), 'G a scrap of text is refused');
await p.fill('#aiKeyInput', ' AQ.Ab8RN6NEWSTYLEKEY_0000000000-x '); await p.locator('#aiKeyForm button[type="submit"]').click(); await p.waitForTimeout(600);
ok(await p.locator('#aiKeyDlg[open]').count() === 0 && (await shelf(p, () => window.__prefs))['gemini.key'] === 'AQ.Ab8RN6NEWSTYLEKEY_0000000000-x', 'G a key in any format (not just AIza…) is accepted and trimmed');
await p.locator('#statusBtn').click(); await p.waitForTimeout(150); await p.locator('#checkMore summary').click(); await p.locator('#checkMore [data-act="ai-key"]').click(); await p.waitForTimeout(150);
await p.fill('#aiKeyInput', GKEY); await p.locator('#aiKeyForm button[type="submit"]').click(); await p.waitForTimeout(600);
ok(await p.locator('#aiKeyDlg[open]').count() === 0 && /Gemini key works/.test(await p.locator('#toast').textContent()), 'G saving a key checks it with Google');
// The key lives only in the phone's storage: not in the web view's storage, the shelf link or the site
const lsAll = await p.evaluate(() => Object.keys(localStorage).map((k) => localStorage.getItem(k)).join(' '));
ok(!lsAll.includes(GKEY) && (await shelf(p, () => window.__prefs))['gemini.key'] === GKEY, 'G the key is kept on the phone only');
await p.locator('#statusBtn').click(); if (!(await p.locator('#checkMore[open]').count())) await p.locator('#checkMore summary').click(); await p.locator('#sendBtn').click(); await p.waitForTimeout(300);
const slink = await clipNow();
ok(!slink.includes(GKEY) && /#shelf=/.test(slink), 'G the shelf link never carries the key');
await p.keyboard.press('Escape');
ok(!fs.readFileSync(root + 'index.html', 'utf8').includes('AIzaGEMINI'), 'G no key in the built site');
const aiCache = (await shelf(p, () => window.__prefs))['shelf.v3.ai'] || '';
ok(/Fake gist/.test(aiCache), 'G summaries are kept on the phone too');
ok(await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'G no sideways scroll');
await ctx.close();

console.log('\n== L Listen (the podcast version, which plays locked)');
({ ctx, p } = await appPage({ fakes: { fresh: false } }));
await settle(p);
await p.locator('.band.c2 .tg').click(); await p.waitForTimeout(100);
await p.locator('.band.c2 .chl button', { hasText: 'Breaking Points' }).click(); await p.waitForTimeout(200);
await p.locator('#page .item', { hasText: 'Polling Mess' }).click(); await p.waitForTimeout(1500);
ok(await p.locator('#vsheet.open').count() === 1 && await p.locator('#vListen').isVisible(), 'L Listen shows on every channel video');
await p.locator('#vListen').click(); await p.waitForTimeout(300);
ok(/doesn't put its videos out as a podcast/.test(await p.locator('#toast').textContent()) && await p.locator('#toast button', { hasText: 'Play locked' }).count() === 1 && await p.locator('#vsheet.open').count() === 1, 'L no podcast for this channel: says so and offers Play locked');
await p.locator('[data-act="close-video"]').first().click(); await p.waitForTimeout(300);
await p.locator('[data-act="back"]').click(); await p.waitForTimeout(150);
await p.locator('.band.c2 .chl button', { hasText: 'The Ezra Klein Show' }).click(); await p.waitForTimeout(200);
await p.locator('#page .item', { hasText: 'Housing Market' }).click();
await p.locator('#vListen').waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
await p.waitForFunction(() => { const t = window.__shelf.twins[window.__shelf.current]; return t && !t.busy; }, null, { timeout: 5000 }).catch(() => {});
ok(await p.locator('#vListen').isVisible(), 'L Ezra Klein video: Listen is there and its podcast episode is already found');
const lb = await p.locator('#vListen').boundingBox(), mb = await p.locator('#vMark').boundingBox();
ok(lb && mb && lb.y >= mb.y && lb.width > 100 && lb.height >= 44, 'L Listen sits with Mark and Notes, full-size tap target');
await p.waitForFunction(() => window.__fake.getPlayerState() === 1, null, { timeout: 5000 }).catch(() => {});
await p.evaluate(() => window.__fake.advance(300)); await p.waitForTimeout(1300);
const vidL = await shelf(p, () => window.__shelf.current);
await p.locator('#vListen').click(); await p.waitForTimeout(700);
const lst = await shelf(p, () => { const st = window.__shelf.engine.state(), g = st.episode && st.episode.guid, r = g && window.__shelf.audio[g]; return { title: st.episode && st.episode.title, rec: r, current: window.__shelf.current, toast: document.querySelector('#toast').textContent }; });
ok(await p.locator('#nsheet.open').count() === 1 && lst.title === 'Why the Housing Market Is Stuck' && !lst.current, 'L Listen closes the video and opens the episode in the sleep player');
ok(lst.rec && lst.rec.video === vidL && /Podcast version from 5:0\d\. You can lock the phone/.test(lst.toast), 'L it starts where the video was and says so: ' + lst.toast.split('.')[0]);
await p.evaluate((v) => window.__shelf.syncTwin({ video: v, t: 450 }), vidL);
const vt = await p.evaluate((v) => window.__shelf.videos[v].t, vidL);
ok(Math.abs(vt - 450) < 1, 'L listening moves the video place along (' + Math.round(vt) + ' s)');
await p.evaluate((v) => window.__shelf.syncTwin({ video: v, t: 200 }), vidL);
ok(Math.abs(await p.evaluate((v) => window.__shelf.videos[v].t, vidL) - 450) < 1, 'L an older listen played again never rewinds the video');
await p.evaluate((v) => { window.__shelf.syncTwin({ video: v, t: 9000 }); window.__shelf.syncTwin({ video: v, t: 9000, done: true }); }, vidL);
const vEnd = await p.evaluate((v) => window.__shelf.videos[v], vidL);
ok(!vEnd.done && vEnd.t === vEnd.dur - 30, 'L the audio never runs the video to its end or ticks it (' + Math.round(vEnd.t) + ' of ' + Math.round(vEnd.dur) + ')');
await p.locator('[data-act="close-night"]').click(); await p.waitForTimeout(200);
await p.locator('#todayBtn').click(); await p.waitForTimeout(200);
const homeHits = await p.locator('#home .band li', { hasText: 'Housing Market' }).count();
ok(homeHits === 1, 'L the episode is not listed again beside its video on Home (' + homeHits + ' rows)');
// Not sure which episode (here: the podcast cut is much longer than the video): Listen offers a short pick list
await p.locator('.band.c2 .chl button', { hasText: 'The Ezra Klein Show' }).click(); await p.waitForTimeout(200);
await p.locator('#page .item', { hasText: 'Boredom' }).click();
await p.waitForFunction(() => { const t = window.__shelf.twins[window.__shelf.current]; return t && !t.busy; }, null, { timeout: 5000 }).catch(() => {});
await p.waitForFunction(() => window.__fake.getPlayerState() === 1, null, { timeout: 5000 }).catch(() => {});
await p.evaluate(() => window.__fake.advance(100)); await p.waitForTimeout(1300);
const vidB = await shelf(p, () => window.__shelf.current), tBefore = await shelf(p, () => window.__fake.getCurrentTime());
await p.locator('#vListen').click(); await p.waitForTimeout(300);
const picks = await p.locator('#twinDlg[open] .tw-ep').count();
ok(picks >= 2 && picks <= 4 && /different length/.test(await p.locator('#twinBody').textContent()) && (await p.locator('#twinDlg .tw-ep.best b').textContent()) === 'The Case for Boredom', 'L unsure: a pick list of ' + picks + ' episodes, the closest on top');
await p.locator('#twinDlg .tw-ep').first().click(); await p.waitForTimeout(600);
const pk = await shelf(p, () => { const st = window.__shelf.engine.state(); return { title: st.episode && st.episode.title, rec: window.__shelf.audio[st.episode.guid], toast: document.querySelector('#toast').textContent }; });
ok(await p.locator('#nsheet.open').count() === 1 && pk.title === 'The Case for Boredom' && !pk.rec.video && /Your place in the video stays/.test(pk.toast), 'L picking plays it in the sleep player, not tied to the video');
ok(Math.abs(await p.evaluate((v) => window.__shelf.videos[v].t, vidB) - tBefore) < 2, 'L the video place is left alone for a different cut');
await ctx.close();

console.log('\n== Mac browser (no app)');
const mctx = await browser.newContext({ viewport: { width: 1280, height: 820 }, permissions: ['clipboard-read', 'clipboard-write'] });
await installFakes(mctx); await mctx.addInitScript('window.__hour = 14.13;');
const m = await mctx.newPage(); m.on('pageerror', (e) => errors.push('mac: ' + e.message));
await m.goto(URL0); await m.waitForTimeout(500);
ok(await m.locator('#webNote').isVisible(), 'mac: says channels load in the iPhone app');
await m.evaluate(() => { const dt = new DataTransfer(); dt.setData('text/plain', 'https://www.youtube.com/watch?v=9bZkp7q19f0&t=1m'); document.body.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true })); });
await m.waitForTimeout(400);
ok(await m.evaluate(() => window.__shelf.current) === '9bZkp7q19f0' && await m.evaluate(() => window.__lastStart) === 57, 'mac: ⌘V plays the link from its &t= time');
ok(await m.locator('#vAiBtn').isHidden() && await m.locator('#vNotes').isHidden() && (await m.evaluate(() => window.__shelf.checks().map((c) => c.text))).includes('AI works in the iPhone app'), 'mac: no AI in the browser, one quiet line in the self-check');
await m.keyboard.press('Escape');
ok(await m.locator('.band.c0').count() === 1, 'mac: pasted video shows under Pasted');
await m.locator('.band.c0 [data-act="paste-url"]').click(); await m.waitForTimeout(150);
ok(await m.locator('#urlDlg[open]').count() === 1, 'mac: + URL next to Pasted opens a link box');
await m.fill('#urlInput', 'hello there'); await m.press('#urlInput', 'Enter'); await m.waitForTimeout(100);
ok(/isn't a YouTube link/.test(await m.locator('#urlMsg').textContent()), 'mac: a non-link says so');
await m.fill('#urlInput', 'https://youtu.be/dQw4w9WgXcQ'); await m.press('#urlInput', 'Enter'); await m.waitForTimeout(400);
ok(await m.locator('#urlDlg[open]').count() === 0 && await m.evaluate(() => window.__shelf.current) === 'dQw4w9WgXcQ', 'mac: a typed link plays');
await m.keyboard.press('Escape'); await m.waitForTimeout(150);
ok((await m.locator('.band.c0 .hd .tm').textContent()).trim().startsWith('2'), 'mac: Pasted counts it: ' + await m.locator('.band.c0 .hd .tm').textContent());
await m.locator('#statusBtn').click();
ok(!(await m.locator('#toneBtn').isVisible()) && !(await m.locator('#ytBtn').isVisible()) && !(await m.locator('#retryBtn').isVisible()) && await m.locator('#statusDot.good').count() === 1, 'mac: all good, no app-only buttons');
await m.locator('#checkMore summary').click(); await m.locator('#sendBtn').click(); await m.waitForTimeout(200);
const link = await m.evaluate(() => navigator.clipboard.readText());
ok(/#shelf=/.test(link), 'mac: shelf link copied');
await m.keyboard.press('Escape');
await m.screenshot({ path: SHOTS + '/e2e-mac.png' });
// the link carries the spot into the phone app
({ ctx, p } = await appPage());
await p.waitForTimeout(800);
await p.locator('#searchBtn').click(); await p.fill('#sq', link); await p.press('#sq', 'Enter'); await p.waitForTimeout(300);
ok(await shelf(p, () => !!window.__shelf.videos['9bZkp7q19f0']), 'phone: pasting the shelf link brings the spots over');
await ctx.close();
// opened as a file
const fctx = await browser.newContext(); await installFakes(fctx);
const fp = await fctx.newPage(); await fp.goto('file://' + root + 'index.html'); await fp.waitForTimeout(400);
await fp.locator('#statusBtn').click(); await fp.waitForTimeout(150);
ok((await fp.locator('#checkList').textContent()).includes('opened the file directly'), 'file: opened-as-file is explained');

ok(errors.length === 0, 'no script errors' + (errors.length ? ': ' + errors.join(' | ') : ''));
await browser.close();
server.close();
console.log(failures ? `\n${failures} FAILED` : '\nALL PASSED');
process.exit(failures ? 1 : 0);
