const assert = require('assert');
const T = require('../src/timer.js');
const now = new Date(2026, 9, 4, 22, 1, 0).getTime();
const s = T.start(30, now);
assert.strictEqual(T.remaining(s, now + 60000), 29 * 60000);
assert.strictEqual(T.label(s, now + 1000), '29:59 left');
assert.strictEqual(T.tick(s, now + 29 * 60000), null);
assert.strictEqual(T.tick(s, now + 30 * 60000), 'stop');
assert.strictEqual(T.clock(s.endsAt), 'about 10:31 pm');
assert.strictEqual(T.clock(new Date(2026, 9, 4, 0, 5).getTime()), 'about 12:05 am');
assert.strictEqual(T.volume(s, now), 1);
assert.strictEqual(T.volume(s, now + 29.5 * 60000), 0.5);
assert.strictEqual(T.volume(s, now + 31 * 60000), 0);
const e = T.start('end', now);
assert.strictEqual(T.remaining(e, now), null);
assert.strictEqual(T.tick(e, now + 1e9, false), null);
assert.strictEqual(T.tick(e, now, true), 'stop');
assert.strictEqual(T.label(e), 'Stops at the end');
assert.strictEqual(T.label(null), 'Sleep timer off');
assert.strictEqual(T.start(0), null);
assert.strictEqual(T.countdown(3723000), '1:02:03');
assert.strictEqual(T.countdown(59001), '1:00');
assert.strictEqual(T.tick(null, now), null);
console.log('timer: all tests passed');
